sudo: required

services:
  - docker

before_script:
  - docker build --tag registre --file Dockerfile .
  - docker build --tag registre-dev --file Dockerfile.dev .

script:
  - docker run registre-dev npm run test